get http://localhost:3000/exercise

###

get http://localhost:3000/exercise/id=3

###

put http://localhost:3000/exercise/id=3
Content-Type: application/json

{
    "exercise_name": "Barbell Shoulder Press"
}

###

post http://localhost:3000/exercise
Content-Type: application/json

{
    "exercise_name": "Dumbbell Shoulder Press"
}

###

delete http://localhost:3000/exercise/id=3

// End exercise table tests
###

get http://localhost:3000/exercise-set

###

post http://localhost:3000/exercise-set
Content-Type: application/json

{
    "exercise_id": "3",
    "sets": "1",
    "repetitions": "12",
    "weight": "35"
}

###

put http://localhost:3000/exercise-set/id=9 
Content-Type: application/json

{
    "sets": "2",
    "repetitions": "6",
    "weight": "45"
}

###

delete http://localhost:3000/exercise-set/id=3
###
// End exercise set table tests

get http://localhost:3000/workout

###

post http://localhost:3000/workout
Content-Type: application/json

{
    "date": "2025-02-14"
}

###

put http://localhost:3000/workout/id=3
Content-Type: application/json

{
    "date": "2025-02-15"
}
###

delete http://localhost:3000/workout/id=3

// End workout table routes tests
###

get http://localhost:3000/workout-exercise

###

post http://localhost:3000/workout-exercise
Content-Type: application/json

{
    "workout_id": "2",
    "exercise_id": "2"
}

###

put http://localhost:3000/workout-exercise/id=4
Content-Type: application/json

{
    "workout_id": "2",
    "exercise_id": "1"
}

###

delete http://localhost:3000/workout-exercise/id=4

###
// End workout exercise junction table routes tests